### PR TITLE
add pgbackrest

### PR DESCRIPTION
**Pull request by carlcsaposs-canonical**

### CODE REVIEW

**Comment by carlcsaposs-canonical** [comment]
Synchronize with launchpad (cherry-pick https://git.launchpad.net/~data-platform/+git/pgbouncer/commit/?h=1.12-20.04&id=365337028de833790abab73cd21eb5f7ae31c830)

**Review by WRFitch — APPROVED** [review]

**Comment by marceloneppel** [comment]
@carlcsaposs-canonical, do you know why pgbackrest is needed in this container image? I think it's needed only in the PostgreSQL container image.

I understood that the motivation for this PR was to synchronise with launchpad, and I saw that it was changed one day after I made a [change on the PostgreSQL container image](https://git.launchpad.net/~data-platform/+git/postgres-patroni/commit/?h=12-20.04), but I don't know why the change was made on the PgBouncer container image.

Do you have additional context about why it's needed to add this package to this specific container image?

**Comment by carlcsaposs-canonical** [comment]
@marceloneppel I have no additional context.

I only saw that the commit was on launchpad & wondered if it should be cherry-picked onto 67bcca7cab51c807c0921ecd27734b6485873139. (it appears that the current OCI image for pgbouncer includes pgbackrest).

Should I try updating the image without the pgbackrest commit?

**Comment by marceloneppel** [comment]
> @marceloneppel I have no additional context.
> 
> I only saw that the commit was on launchpad & wondered if it should be cherry-picked onto [67bcca7](https://github.com/canonical/pgbouncer-container/commit/67bcca7cab51c807c0921ecd27734b6485873139). (it appears that the current OCI image for pgbouncer includes pgbackrest).
> 
> Should I try updating the image without the pgbackrest commit?

Let's ask @delgod next week if was him that asked Paulo to add pgbackrest to pgbouncer container. I saw that there is an option to do a remote backup using pgbackrest, but I don't think the pgbouncer server would be a candidate for a backup server (the one that asks for and stores the remote backup).

We probably will remove pgbackrest from this container image, but let's get the answer for the above question first.

**Comment by carlcsaposs-canonical** [comment]
Is it okay to leave the OCI image outdated in the meantime?

**Comment by marceloneppel** [comment]
> Is it okay to leave the OCI image outdated in the meantime?

@carlcsaposs-canonical, I checked again my discussion with Paulo at the time of the commit, and I saw that we were talking about pgbouncer rocks image and also about adding pgbackrest to the postgresql container image, so we mixed those topics and that caused pgbouncer to be incorrectly added to the pgbouncer container image. So, now, you can remove pgbackrest from the image (it's not needed on pgbouncer)

**Pull request closed without merging**
